'use strict';

const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const Hexo = require('hexo');
const registerPlugin = require('..');

test('generates article previews, CTA, learning page, and assets in a real Hexo site', async (t) => {
  const pluginRoot = path.resolve(__dirname, '..');
  const fixtureRoot = path.join(__dirname, 'fixtures', 'site');
  const siteRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'hexo-flashcard-plugin-'));
  fs.cpSync(fixtureRoot, siteRoot, { recursive: true });
  fs.symlinkSync(path.join(pluginRoot, 'node_modules'), path.join(siteRoot, 'node_modules'), 'dir');

  const hexo = new Hexo(siteRoot, { silent: true });
  hexo.env.init = true;
  t.after(async () => {
    await hexo.exit();
    fs.rmSync(siteRoot, { recursive: true, force: true });
  });
  await hexo.init();
  registerPlugin(hexo);
  await hexo.load();
  await hexo.call('generate', {});

  const postHtml = fs.readFileSync(path.join(siteRoot, 'public', 'demo', 'index.html'), 'utf8');
  const referenceHtml = fs.readFileSync(path.join(siteRoot, 'public', 'reference', 'index.html'), 'utf8');
  const learningHtml = fs.readFileSync(path.join(siteRoot, 'public', 'learn-topic', 'index.html'), 'utf8');
  const css = fs.readFileSync(path.join(siteRoot, 'public', 'flashcard-assets', 'flashcard.css'), 'utf8');
  const js = fs.readFileSync(path.join(siteRoot, 'public', 'flashcard-assets', 'flashcard.js'), 'utf8');
  const syncJs = fs.readFileSync(path.join(siteRoot, 'public', 'flashcard-assets', 'flashcard-sync.js'), 'utf8');
  const fsrs = fs.readFileSync(path.join(siteRoot, 'public', 'flashcard-assets', 'ts-fsrs.umd.js'), 'utf8');
  const supabase = fs.readFileSync(path.join(siteRoot, 'public', 'flashcard-assets', 'supabase.js'), 'utf8');
  const cardIndex = JSON.parse(fs.readFileSync(path.join(siteRoot, 'public', 'flashcard-assets', 'cards', 'index.json'), 'utf8'));

  assert.match(postHtml, /data-hfc-inline/);
  assert.match(postHtml, /复习本篇 · 3 张卡片/);
  assert.match(postHtml, /data-hfc-article-count="3"/);
  assert.match(postHtml, /aria-label="复习本篇 · 3 张卡片"/);
  assert.match(postHtml, /fas fa-graduation-cap hfc-review-icon/);
  assert.match(postHtml, /hfc-review-label">复习</);
  assert.match(postHtml, /flashcard-assets\/flashcard\.css/);
  assert.match(postHtml, /flashcard-assets\/ts-fsrs\.umd\.js/);
  assert.match(postHtml, /flashcard-assets\/supabase\.js/);
  assert.match(postHtml, /flashcard-assets\/flashcard-sync\.js/);
  assert.match(postHtml, /flashcard-assets\/flashcard\.js/);
  assert.match(postHtml, /Q01/);
  assert.match(postHtml, /#状态码/);
  assert.match(postHtml, /hfc-priority--1[^>]*href="\/learn-topic\/\?priority=1"[^>]*>高频<\/a>/);
  assert.match(postHtml, /hfc-priority--2[^>]*>中频<\/a>/);
  assert.match(postHtml, /hfc-priority--3[^>]*>低频<\/a>/);
  assert.doesNotMatch(postHtml, /class="hfc-type"/);
  assert.match(postHtml, /问题:/);
  assert.match(postHtml, /回答：/);
  assert.match(postHtml, /解析：/);
  assert.doesNotMatch(postHtml, /{%\s*flashcard/);

  assert.match(referenceHtml, /复习本篇 · 2 张卡片/);
  assert.equal((referenceHtml.match(/data-card-id="http-404"/g) || []).length, 1);
  assert.equal((referenceHtml.match(/data-card-id="http-method"/g) || []).length, 1);
  assert.match(referenceHtml, /Q01/);
  assert.match(referenceHtml, /Q02/);
  assert.doesNotMatch(referenceHtml, /{%\s*flashcard_ref/);

  assert.match(learningHtml, /data-hfc-app/);
  assert.match(learningHtml, /data-hfc-plan/);
  assert.match(learningHtml, /data-hfc-sync/);
  assert.match(learningHtml, /使用 GitHub 登录并同步/);
  assert.match(learningHtml, /<title>复习<\/title>/);
  assert.match(learningHtml, /<h1>复习<\/h1>/);
  assert.match(learningHtml, /"cardIndexUrl":"\/flashcard-assets\/cards\/index\.json"/);
  assert.doesNotMatch(learningHtml, /hfc-card-data/);
  assert.doesNotMatch(learningHtml, /HTTP 404 表示什么/);
  assert.doesNotMatch(learningHtml, /服务器没有找到目标资源/);
  assert.equal(cardIndex.length, 4);
  assert.deepEqual(cardIndex.map((card) => card.id).sort(), ['http-404', 'http-cache', 'http-method', 'http-success']);
  assert.deepEqual(Object.fromEntries(cardIndex.map((card) => [card.id, card.priority])), {
    'http-404': 1,
    'http-cache': 2,
    'http-method': 2,
    'http-success': 3
  });
  assert.deepEqual(cardIndex.find((card) => card.id === 'http-404').articles.map((article) => article.articlePath), ['demo/', 'reference/']);
  assert.ok(cardIndex.every((card) => /^[0-9]{2}$/.test(card.shard)));
  assert.ok(cardIndex.every((card) => !Object.hasOwn(card, 'questionHtml') && !Object.hasOwn(card, 'answerHtml') && !Object.hasOwn(card, 'explanationHtml')));
  const shardCards = cardIndex.flatMap((entry) => JSON.parse(fs.readFileSync(path.join(siteRoot, 'public', 'flashcard-assets', 'cards', `${entry.shard}.json`), 'utf8')));
  assert.ok(shardCards.some((card) => card.id === 'http-404' && card.questionHtml && card.answerHtml && card.explanationHtml));
  assert.doesNotMatch(learningHtml, /1、3、7、14、30、60、120 天/);
  assert.match(css, /\.hfc-rating__grid/);
  assert.match(css, /grid-template-columns:\s*4\.2rem minmax\(0, 1fr\)/);
  assert.match(css, /\.hfc-app\s*{[^}]*width:\s*100%;/s);
  assert.match(css, /--hfc-surface:\s*linear-gradient\(135deg, rgba\(220, 243, 242, 0\.98\) 0%, rgba\(245, 243, 237, 0\.98\) 52%, rgba\(247, 220, 213, 0\.96\) 100%\);/);
  assert.match(css, /--hfc-option-bg:\s*rgba\(249, 247, 241, 0\.58\);/);
  assert.match(css, /\[data-theme='dark'\] \.hfc-app,[\s\S]*--hfc-bg:\s*var\(--card-bg, rgba\(18, 18, 18, 0\.94\)\);/);
  assert.match(css, /\[data-theme='dark'\] \.hfc-app,[\s\S]*--hfc-surface:\s*var\(--card-bg, #121212\);/);
  assert.match(css, /\.hfc-study-card\s*{[^}]*width:\s*100%;/s);
  assert.match(css, /\.hfc-inline\s*{[^}]*display:\s*block;[^}]*width:\s*100%;/s);
  assert.doesNotMatch(css, /calc\(50% - 10px\)/);
  assert.match(css, /\.hfc-question\s*{[^}]*display:\s*flex;[^}]*justify-content:\s*center;/s);
  assert.match(css, /\.hfc-options\s*{[^}]*width:\s*100%;[^}]*margin:\s*18px 0 0;/s);
  assert.match(css, /\.hfc-options > div > :last-child\s*{[^}]*margin:\s*0\s*!important;/s);
  assert.match(css, /\.hfc-number\s*{[^}]*font-size:\s*1rem;[^}]*font-weight:\s*900;/s);
  assert.match(css, /\.hfc-priority--1\s*{[^}]*linear-gradient\(135deg, #ff7a7a, #ff4757\)/s);
  assert.match(css, /\.hfc-priority--2\s*{[^}]*linear-gradient\(135deg, #ffe08a, #f3b43f\)/s);
  assert.match(css, /\.hfc-priority--3\s*{[^}]*linear-gradient\(135deg, #68dd9a, #2fbd70\)/s);
  assert.match(css, /\.hfc-session\s*{[^}]*border-radius:\s*28px;/s);
  assert.match(css, /\.hfc-session-progress span\s*{[^}]*width:\s*var\(--hfc-session-progress, 0%\);/s);
  assert.match(css, /\.hfc-session-metrics\s*{/);
  assert.match(css, /\.hfc-session-metric--done\s*{[^}]*#55a878/s);
  assert.match(css, /\.hfc-calendar-grid\s*{[^}]*grid-template-columns:\s*repeat\(7, minmax\(0, 1fr\)\);/s);
  assert.match(css, /\.hfc-calendar-day\.is-complete \.hfc-calendar-ring\s*{[^}]*#42c98b[^}]*#8adf76/s);
  assert.match(css, /\.hfc-calendar-day\.is-missed \.hfc-calendar-ring\s*{[^}]*#ff6b72[^}]*#ef8a5d/s);
  assert.match(css, /\.hfc-drawer__panel\s*{[^}]*width:\s*min\(92vw, 520px\);/s);
  assert.match(css, /\.hfc-drawer-question\s*{[^}]*overflow-wrap:\s*anywhere;/s);
  assert.match(css, /@keyframes hfc-memory-orbit/);
  assert.match(css, /\.post-reward > \.hfc-article-cta--reward/);
  assert.match(css, /\.post-reward\.hfc-review-hovering > \.reward-main\s*{[^}]*display:\s*none\s*!important;/s);
  assert.match(css, /@keyframes hfc-review-icon-swing/);
  assert.match(css, /\.hfc-flip\.is-flipped/);
  assert.match(css, /--default-bg-color/);
  assert.match(js, /hexo-flashcard-plugin:v3/);
  assert.match(js, /hexo-flashcard-plugin:v2/);
  assert.match(js, /这张卡记得如何？/);
  assert.match(js, />开始<\/button>/);
  assert.doesNotMatch(js, /开始学习新卡/);
  assert.match(js, /hfc-session--empty/);
  assert.match(js, /hfc-session-progress/);
  assert.match(js, /DRAWER_BATCH_SIZE = 20/);
  assert.match(js, /const PRIORITY_LABELS = \{ 1: '高频', 2: '中频', 3: '低频' \}/);
  assert.match(js, /params\.get\('priority'\)/);
  assert.match(js, /left\.priority - right\.priority/);
  assert.match(js, /progress\.cards\[left\.id\]\.due - progress\.cards\[right\.id\]\.due/);
  assert.match(js, /function loadCardContent/);
  assert.match(js, /function renderCalendar/);
  assert.match(js, /function openDrawer/);
  assert.match(js, /复习计划/);
  assert.match(js, /完成一次复习后，这里会显示后续安排/);
  assert.match(js, /继续加载 20 题/);
  assert.match(js, /placeArticleReviewActions/);
  assert.match(js, /hfc-review-hovering/);
  assert.match(js, /record\(card, button\.dataset\.hfcRate, reviewedAt\)/);
  assert.match(js, /scheduler\.next\(deserializeCard\(previous, reviewedAt\), new Date\(reviewedAt\), RATING_VALUES\[rating\]\)/);
  assert.match(fsrs, /global\.FSRS/);
  assert.match(syncJs, /sync_flashcard_progress/);
  assert.match(syncJs, /reset_flashcard_progress/);
  assert.match(supabase, /createClient/);
});
